### ISSUE TITLE
Convert NAD83 XCoord/YCoord to NAD83 (or WGS84) Lon/Lat

### ISSUE THREAD

**Issue by kylesykes** [kylesykes/stl-crime-data#7]
Preferably in the cleaning script so it's transparent what transformations took place.
NAD83 or WGS84 should be alright for the purposes of this dataset since they are relatively close (1~1.5m off).

**Comment by dgarbuz** [comment]
Script that will convert is done!

**Comment by dgarbuz** [comment]
Converted. I am going to keep this issue open to see if everything works when we put the data on a map.

**Comment by kylesykes** [comment]
Closing.  If there's an issue, we open a new issue! :)
